/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"
#import "TAsyncRegister.h"
#import "TMemoryBuffer.h"
#import "TBinaryProtocol.h"
#import "TExceptionRegister.h"

#import "types.h"
#import "exceptions.h"

@protocol THClientService <NSObject>
- (BOOL) onPing: (NSString *) arg;  // throws TException
@end

@interface THClientServiceClient : TBaseClient <THClientService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface THClientServiceProcessor : NSObject <TProcessor> {
  id <THClientService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithClientService: (id <THClientService>) service;
- (id<THClientService>) service;
@end

@protocol THClientServiceAsync <NSObject>
- (void) onPing: (NSString *) arg success: (void (^)(BOOL result)) success error: (void (^)(NSException *exception)) error;  // throws TException
@end

@interface THClientServiceAsyncClient : NSObject <THClientServiceAsync> {
id <TProtocol> outProtocol;
id <TProtocolFactory> inProtocolFactory;
}
- (id) initWithOutProtocol: (id <TProtocol>) outProtocol inProtocolFactory: (id <TProtocolFactory>) inProtocolFactory;
@end

@interface THClientServiceConstants : NSObject {
}
@end
