/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"
#import "TAsyncRegister.h"
#import "TMemoryBuffer.h"
#import "TBinaryProtocol.h"
#import "TExceptionRegister.h"

#import "types.h"
#import "exceptions.h"

@protocol THTotalkService <NSObject>
- (NSString *) hello: (NSString *) arg;  // throws AuthenticationRequiredException *, TException
- (void) ping: (NSString *) arg;  // throws AuthenticationRequiredException *, TException
- (THReview *) getReviewById: (NSString *) id;  // throws NoReviewException *, TException
- (NSMutableArray *) getByCreatedAt: (int) country categoryId: (int32_t) categoryId offset: (int32_t) offset limit: (int32_t) limit;  // throws TException
- (NSMutableArray *) getByPopularity: (int) country categoryId: (int32_t) categoryId offset: (int32_t) offset limit: (int32_t) limit arg3: (int64_t) arg3;  // throws TException
- (NSMutableArray *) getSubscription: (NSString *) userId categoryId: (int32_t) categoryId;  // throws TException
- (NSMutableArray *) getComments: (NSString *) reviewId offset: (int32_t) offset limit: (int32_t) limit;  // throws NoReviewException *, TException
- (NSMutableArray *) getByEntity: (int) entityType entityId: (NSString *) entityId reviewType: (int) reviewType offset: (int32_t) offset limit: (int32_t) limit;  // throws TException
- (void) setVote: (NSString *) reviewId yes: (BOOL) yes;  // throws NoReviewException *, TException
- (THReview *) addReview: (THReview *) review;  // throws TException
- (THComment *) addComment: (THComment *) comment;  // throws TException
@end

@interface THTotalkServiceClient : TBaseClient <THTotalkService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface THTotalkServiceProcessor : NSObject <TProcessor> {
  id <THTotalkService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithTotalkService: (id <THTotalkService>) service;
- (id<THTotalkService>) service;
@end

@protocol THTotalkServiceAsync <NSObject>
- (void) hello: (NSString *) arg success: (void (^)(NSString * result)) success error: (void (^)(NSException *exception)) error;  // throws AuthenticationRequiredException *, TException
- (void) ping: (NSString *) arg success: (void (^)(void)) success error: (void (^)(NSException *exception)) error;  // throws AuthenticationRequiredException *, TException
- (void) getReviewById: (NSString *) id success: (void (^)(THReview * result)) success error: (void (^)(NSException *exception)) error;  // throws NoReviewException *, TException
- (void) getByCreatedAt: (int) country categoryId: (int32_t) categoryId offset: (int32_t) offset limit: (int32_t) limit success: (void (^)(NSMutableArray * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
- (void) getByPopularity: (int) country categoryId: (int32_t) categoryId offset: (int32_t) offset limit: (int32_t) limit arg3: (int64_t) arg3 success: (void (^)(NSMutableArray * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
- (void) getSubscription: (NSString *) userId categoryId: (int32_t) categoryId success: (void (^)(NSMutableArray * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
- (void) getComments: (NSString *) reviewId offset: (int32_t) offset limit: (int32_t) limit success: (void (^)(NSMutableArray * result)) success error: (void (^)(NSException *exception)) error;  // throws NoReviewException *, TException
- (void) getByEntity: (int) entityType entityId: (NSString *) entityId reviewType: (int) reviewType offset: (int32_t) offset limit: (int32_t) limit success: (void (^)(NSMutableArray * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
- (void) setVote: (NSString *) reviewId yes: (BOOL) yes success: (void (^)(void)) success error: (void (^)(NSException *exception)) error;  // throws NoReviewException *, TException
- (void) addReview: (THReview *) review success: (void (^)(THReview * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
- (void) addComment: (THComment *) comment success: (void (^)(THComment * result)) success error: (void (^)(NSException *exception)) error;  // throws TException
@end

@interface THTotalkServiceAsyncClient : NSObject <THTotalkServiceAsync> {
id <TProtocol> outProtocol;
id <TProtocolFactory> inProtocolFactory;
}
- (id) initWithOutProtocol: (id <TProtocol>) outProtocol inProtocolFactory: (id <TProtocolFactory>) inProtocolFactory;
@end

@interface THTotalkServiceConstants : NSObject {
}
@end
