/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"
#import "TAsyncRegister.h"
#import "TMemoryBuffer.h"
#import "TBinaryProtocol.h"
#import "TExceptionRegister.h"


enum THReviewType {
  ReviewType_OPINION = 0,
  ReviewType_REVIEW = 1
};

enum THEntityType {
  EntityType_ADV = 0
};

enum THCountry {
  Country_RU = 0,
  Country_CN = 1
};

@interface THComment : NSObject <TBase, NSCoding> {
  NSString * __id;
  NSString * __reviewId;
  BOOL __deleted;
  int64_t __deletedAt;
  NSString * __creatorId;
  NSString * __createdAt;

  BOOL __id_isset;
  BOOL __reviewId_isset;
  BOOL __deleted_isset;
  BOOL __deletedAt_isset;
  BOOL __creatorId_isset;
  BOOL __createdAt_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=reviewId, setter=setReviewId:) NSString * reviewId;
@property (nonatomic, getter=deleted, setter=setDeleted:) BOOL deleted;
@property (nonatomic, getter=deletedAt, setter=setDeletedAt:) int64_t deletedAt;
@property (nonatomic, retain, getter=creatorId, setter=setCreatorId:) NSString * creatorId;
@property (nonatomic, retain, getter=createdAt, setter=setCreatedAt:) NSString * createdAt;
#endif

- (id) init;
- (id) initWithId: (NSString *) id reviewId: (NSString *) reviewId deleted: (BOOL) deleted deletedAt: (int64_t) deletedAt creatorId: (NSString *) creatorId createdAt: (NSString *) createdAt;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) reviewId;
- (void) setReviewId: (NSString *) reviewId;
#endif
- (BOOL) reviewIdIsSet;

#if !__has_feature(objc_arc)
- (BOOL) deleted;
- (void) setDeleted: (BOOL) deleted;
#endif
- (BOOL) deletedIsSet;

#if !__has_feature(objc_arc)
- (int64_t) deletedAt;
- (void) setDeletedAt: (int64_t) deletedAt;
#endif
- (BOOL) deletedAtIsSet;

#if !__has_feature(objc_arc)
- (NSString *) creatorId;
- (void) setCreatorId: (NSString *) creatorId;
#endif
- (BOOL) creatorIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createdAt;
- (void) setCreatedAt: (NSString *) createdAt;
#endif
- (BOOL) createdAtIsSet;

@end

@interface THReview : NSObject <TBase, NSCoding> {
  NSString * __id;
  int __type;
  BOOL __deleted;
  int64_t __deletedAt;
  int __entityType;
  NSString * __entityId;
  int32_t __categoryId;
  int __country;
  NSString * __creatorId;
  int64_t __createdAt;
  int64_t __updatedAt;
  BOOL __commentsAllowed;
  NSString * __title;
  NSString * __body;
  int32_t ___votesYes;
  int64_t __votesYes;
  int32_t __votesNo;
  NSMutableArray * __comments;
  int32_t __reviewsCount;
  BOOL __myVote;

  BOOL __id_isset;
  BOOL __type_isset;
  BOOL __deleted_isset;
  BOOL __deletedAt_isset;
  BOOL __entityType_isset;
  BOOL __entityId_isset;
  BOOL __categoryId_isset;
  BOOL __country_isset;
  BOOL __creatorId_isset;
  BOOL __createdAt_isset;
  BOOL __updatedAt_isset;
  BOOL __commentsAllowed_isset;
  BOOL __title_isset;
  BOOL __body_isset;
  BOOL ___votesYes_isset;
  BOOL __votesYes_isset;
  BOOL __votesNo_isset;
  BOOL __comments_isset;
  BOOL __reviewsCount_isset;
  BOOL __myVote_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, getter=deleted, setter=setDeleted:) BOOL deleted;
@property (nonatomic, getter=deletedAt, setter=setDeletedAt:) int64_t deletedAt;
@property (nonatomic, getter=entityType, setter=setEntityType:) int entityType;
@property (nonatomic, retain, getter=entityId, setter=setEntityId:) NSString * entityId;
@property (nonatomic, getter=categoryId, setter=setCategoryId:) int32_t categoryId;
@property (nonatomic, getter=country, setter=setCountry:) int country;
@property (nonatomic, retain, getter=creatorId, setter=setCreatorId:) NSString * creatorId;
@property (nonatomic, getter=createdAt, setter=setCreatedAt:) int64_t createdAt;
@property (nonatomic, getter=updatedAt, setter=setUpdatedAt:) int64_t updatedAt;
@property (nonatomic, getter=commentsAllowed, setter=setCommentsAllowed:) BOOL commentsAllowed;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=body, setter=setBody:) NSString * body;
@property (nonatomic, getter=_votesYes, setter=set_votesYes:) int32_t _votesYes;
@property (nonatomic, getter=votesYes, setter=setVotesYes:) int64_t votesYes;
@property (nonatomic, getter=votesNo, setter=setVotesNo:) int32_t votesNo;
@property (nonatomic, retain, getter=comments, setter=setComments:) NSMutableArray * comments;
@property (nonatomic, getter=reviewsCount, setter=setReviewsCount:) int32_t reviewsCount;
@property (nonatomic, getter=myVote, setter=setMyVote:) BOOL myVote;
#endif

- (id) init;
- (id) initWithId: (NSString *) id type: (int) type deleted: (BOOL) deleted deletedAt: (int64_t) deletedAt entityType: (int) entityType entityId: (NSString *) entityId categoryId: (int32_t) categoryId country: (int) country creatorId: (NSString *) creatorId createdAt: (int64_t) createdAt updatedAt: (int64_t) updatedAt commentsAllowed: (BOOL) commentsAllowed title: (NSString *) title body: (NSString *) body _votesYes: (int32_t) _votesYes votesYes: (int64_t) votesYes votesNo: (int32_t) votesNo comments: (NSMutableArray *) comments reviewsCount: (int32_t) reviewsCount myVote: (BOOL) myVote;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int) type;
- (void) setType: (int) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) deleted;
- (void) setDeleted: (BOOL) deleted;
#endif
- (BOOL) deletedIsSet;

#if !__has_feature(objc_arc)
- (int64_t) deletedAt;
- (void) setDeletedAt: (int64_t) deletedAt;
#endif
- (BOOL) deletedAtIsSet;

#if !__has_feature(objc_arc)
- (int) entityType;
- (void) setEntityType: (int) entityType;
#endif
- (BOOL) entityTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) entityId;
- (void) setEntityId: (NSString *) entityId;
#endif
- (BOOL) entityIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) categoryId;
- (void) setCategoryId: (int32_t) categoryId;
#endif
- (BOOL) categoryIdIsSet;

#if !__has_feature(objc_arc)
- (int) country;
- (void) setCountry: (int) country;
#endif
- (BOOL) countryIsSet;

#if !__has_feature(objc_arc)
- (NSString *) creatorId;
- (void) setCreatorId: (NSString *) creatorId;
#endif
- (BOOL) creatorIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) createdAt;
- (void) setCreatedAt: (int64_t) createdAt;
#endif
- (BOOL) createdAtIsSet;

#if !__has_feature(objc_arc)
- (int64_t) updatedAt;
- (void) setUpdatedAt: (int64_t) updatedAt;
#endif
- (BOOL) updatedAtIsSet;

#if !__has_feature(objc_arc)
- (BOOL) commentsAllowed;
- (void) setCommentsAllowed: (BOOL) commentsAllowed;
#endif
- (BOOL) commentsAllowedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) body;
- (void) setBody: (NSString *) body;
#endif
- (BOOL) bodyIsSet;

#if !__has_feature(objc_arc)
- (int32_t) _votesYes;
- (void) set_votesYes: (int32_t) _votesYes;
#endif
- (BOOL) _votesYesIsSet;

#if !__has_feature(objc_arc)
- (int64_t) votesYes;
- (void) setVotesYes: (int64_t) votesYes;
#endif
- (BOOL) votesYesIsSet;

#if !__has_feature(objc_arc)
- (int32_t) votesNo;
- (void) setVotesNo: (int32_t) votesNo;
#endif
- (BOOL) votesNoIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) comments;
- (void) setComments: (NSMutableArray *) comments;
#endif
- (BOOL) commentsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) reviewsCount;
- (void) setReviewsCount: (int32_t) reviewsCount;
#endif
- (BOOL) reviewsCountIsSet;

#if !__has_feature(objc_arc)
- (BOOL) myVote;
- (void) setMyVote: (BOOL) myVote;
#endif
- (BOOL) myVoteIsSet;

@end

@interface THtypesConstants : NSObject {
}
@end
