//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


if (typeof totalk === 'undefined') {
  totalk = {};
}
if (typeof totalk.thrift === 'undefined') {
  totalk.thrift = {};
}
totalk.thrift.NoReviewException = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
Thrift.inherits(totalk.thrift.NoReviewException, Thrift.TException);
totalk.thrift.NoReviewException.prototype.name = 'NoReviewException';
totalk.thrift.NoReviewException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

totalk.thrift.NoReviewException.prototype.write = function(output) {
  output.writeStructBegin('NoReviewException');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

totalk.thrift.AuthenticationRequiredException = function(args) {
};
Thrift.inherits(totalk.thrift.AuthenticationRequiredException, Thrift.TException);
totalk.thrift.AuthenticationRequiredException.prototype.name = 'AuthenticationRequiredException';
totalk.thrift.AuthenticationRequiredException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

totalk.thrift.AuthenticationRequiredException.prototype.write = function(output) {
  output.writeStructBegin('AuthenticationRequiredException');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

