/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tobox.totalk.thrift.types;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EntityType implements org.apache.thrift.TEnum {
  ADV(0);

  private final int value;

  private EntityType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  public int getValueForBit() {
    return 1<<value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EntityType findByValue(int value) { 
    switch (value) {
      case 0:
        return ADV;
      default:
        return null;
    }
  }
}
